<!DOCTYPE html>
<html lang="ua">
<head>
	<meta charset="utf-8">
<title>Главная</title>
<link rel="stylesheet" href="/static/styles/style.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" charset="utf-8"></script>

</head>
<body>

		<header class="header">
				<div class="container">
					<div class="header_inner">
						<div class="header_logo">
							<img src="static/images/activebox-logo.png" alt="">
						</div>
						
						<nav class="nav">
							<a class="nav_link" href="#">Who we are</a>
							<a class="nav_link" href="#">How is it working</a>
							<a class="nav_link" href="#">Blog</a>
						</nav>
					</div>
				</div>
		</header>




        <div class="content">




	</div>
<?=$content?>

	
	<footer>© Klyusko Volodymyr, 2019  </footer>
</body>
</html>