	<a href="/">на главную</a>	
	<h2>Регистрация</h2>
	<div class="auth">
		<div class="auth_item">
		<form action="/registration" method="post">
			<?if(isset($err['empty_field'])):?><div>Вы не заполнили все поля</div><?endif?>
			<?if(isset($err['wrong_check_login'])):?><div>Даный логин существует</div><?endif?>
			<?if(isset($err['wrong_check_nickname'])):?><div>Даный никнейм существует</div><?endif?>
			<?if(isset($err['add_user_fail'])):?><div>Не удалось создать пользователя</div><?endif?>
			<div class="field_row">Логин: <br /><input class="field" name="login" /></div>
			<div class="field_row">Никнейм: <br /><input type="nickname" class="field" name="nickname" /></div>
			<div class="field_row">Пароль: <br /><input type="password" class="field" name="password" /></div>
			<input type="submit" value="Отправить" />
		</form>
		</div>
	</div>