l<div class="questionnaire">
    <div class="container">
        <div class="line"> Place for the line       </div>
        <div class="favicons">
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/consume.svg" height="34" alt="">
                <p class="favicons_title">Consumo</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/home.svg" height="34" alt="">
                <p class="favicons_title">Holgar</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/newVehicle.svg" height="34" alt="">
                <p class="favicons_title">Nuevo Vehículo</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/usedVehicle.svg" height="34" alt="">
                <p class="favicons_title">Vehículo de Ocasión</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/studies.svg" height="34" alt="">
                <p class="favicons_title">Estudios</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/travel.svg" height="34" alt="">
                <p class="favicons_title">Viaje</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/health.svg" height="34" alt="">
                <p class="favicons_title">Salud</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/electronics.svg" height="34" alt="">
                <p class="favicons_title">Electrónica</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/newBusiness.svg" height="34" alt="">
                <p class="favicons_title">Nuevo Negocio</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/helpBusiness.svg" height="34" alt="">
                <p class="favicons_title">Ayuda Negocio</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/reuniteDebts.svg" height="34" alt="">
                <p class="favicons_title">Reunificar deudas</p>
            </div>
            <div class="favicons_item">
                <img src="static/images/favicons/spheres/others.svg" height="34" alt="">
                <p class="favicons_title">Otros</p>
            </div>

        </div>
    </div>
</div>