	<h2>Мої дані</h2>
	<form action="/" method="post">
		<div class="field_row">
			Нікнейм: <br />
			<input class="field" name="nickname" />
		</div>
		<div class="field_row">
			Дата народження 
			<span class="field_descr">(рррр-мм-дд): </span><br />
			<input class="field" name="born" />
		</div>
		<div class="field_row">
			Стать: <br />
			<select name="gender"> 
				<option value=""></option>
				<option value="m">чоловіча</option>
				<option value="f">жіноча</option>
			</select>
		</div>
		<input type="submit" value="Відправити" />
	</form>